### ISSUE TITLE
Plain date time format on the list of files

### ISSUE THREAD

**Issue by fairking** [nextcloud/nextcloud-files#341]
Is there any option to make the `Modified` column show the date and time in plain format?
I would like to move my files to the separated folders by month, but I am not able to see the month and a year of those files:
![image](https://user-images.githubusercontent.com/13495631/142760109-d7d44503-4b96-4599-9812-61688515f1b3.png)

**Comment by fairking** [comment]
Another problem is I cannot select many files from/to by holding `Shift`.

**Comment by fairking** [comment]
And another one issue:
![image](https://user-images.githubusercontent.com/13495631/142761265-1815ce75-fe12-4db1-afe9-c47b03c3e0d9.png)

**Comment by ChristophWurst** [comment]
please see the repo description

> Nextcloud Files helpers for Nextcloud apps and libraries

this is just a library. this has nothing to do with the nextcloud *Files* app.

Please look for existing issues in https://github.com/nextcloud/server/issues and create a new ticket otherwise following the issue template :v:
