### ISSUE TITLE
I cannot select many files

### ISSUE THREAD

**Issue by fairking** [nextcloud/nextcloud-files#342]
The problem is I cannot select many files from/to by holding `Shift`.

![image](https://user-images.githubusercontent.com/13495631/142761341-69cb31c7-7195-4f34-b986-ed0fd95fab3d.png)

**Comment by ChristophWurst** [comment]
please see the repo description

> Nextcloud Files helpers for Nextcloud apps and libraries

this is just a library. this has nothing to do with the nextcloud *Files* app.

Please look for existing issues in https://github.com/nextcloud/server/issues and create a new ticket otherwise following the issue template :v:
