### ISSUE TITLE
When moving files a new created folder is not selected

### ISSUE THREAD

**Issue by fairking** [nextcloud/nextcloud-files#343]
Aftre creating a new folder the button `Move To` keeps saing it is a parent folder.

![image](https://user-images.githubusercontent.com/13495631/142761404-89ecd1bf-e074-4943-8102-4a5c8cdb92a9.png)

**Comment by ChristophWurst** [comment]
please see the repo description

> Nextcloud Files helpers for Nextcloud apps and libraries

this is just a library. this has nothing to do with the nextcloud *Files* app.

Please look for existing issues in https://github.com/nextcloud/server/issues and create a new ticket otherwise following the issue template :v:
