### ISSUE TITLE
GUI of files_external doesn´t allow adding or even to modify existing paths

### ISSUE THREAD

**Issue by simpassy** [nextcloud/nextcloud-files#352]
Version
Nextcloud Hub II (23.0.0)

GUI of files_external doesn't allow adding or even re-moving existing paths any more.

This behaviour happened after adding the official backup app.
No action button is available any more.
No path can be added or removed.

Please take a look at the attached
![files_external](https://user-images.githubusercontent.com/31965315/146385966-aab109bf-ef65-40d5-8d00-422a4c5dc8c6.png)
 png-file

system report :
https://mauel.ddns.net/index.php/s/eim47S5kAi7K4S7
Passwort: Q9muUWJ3vD

**Comment by ChristophWurst** [comment]
Wrong repo. Please use the server repo.

**Comment by simpassy** [comment]
I just used OCC
It´s OK for me
