### ISSUE TITLE
To allow ordering of files in manner of "folders first", as it is ususal in verious file managers

### ISSUE THREAD

**Issue by ratermir** [nextcloud/nextcloud-files#430]
In most file managers (from the oldest Norton Commander, Total Commander, too Windows file manager ... etc) it is usual that directories (aka folders) are placed before the files. Both are sorted by seleced order - i.e. if I choose (for example) ordering by date, the tool place all directories ordered by date forst, then all files ordered by date. The same for ordering by name, size ... etc. 

In the opposite Nextcloud places all in one "heap" which is uncommon. It would be great if NC Files respected this - common and usual - behaviour. 

For the backward compatibility with current NC behavour, this new behavoiur could be enabled / disabled by some setting - etither on system level settings, in user settings or both (i.e. user could accept system setting (this could be default), or could "override" it by its own setting).

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/issues/new/choose
