### ISSUE TITLE
To rearrange icons in Files app to put "plus" button at the fixed position

### ISSUE THREAD

**Issue by ratermir** [nextcloud/nextcloud-files#431]
In the Nextcloud Files - on the top - there is the "+" button to add new element (file, folder ... etc).
It is positiones on the right of current folder which resuts in it mover to right as the current path changes.

The better solution would be to put this button at the fixed position at the beginning of the area - as it is shown on te attached picture.
The result would be always the same position of the button and therefore better UX (easier navigation - always to the same position).

More (with the pictures) is in the ticket I've created in the "Server" part: https://github.com/nextcloud/server/issues/32669
(because this behavour can have wider effect), but the most effect it could have in the "Files".

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/issues/new/choose
