### ISSUE TITLE
PHP error Undefined offset

### ISSUE THREAD

**Issue by giftedsheep** [nextcloud/nextcloud-files#44]
Hello! I was going through the log of my server and noticed some errors that im not sure what they mean and if they are seriously impacting the server. If you have an idea, i would highly appreciate your input. 
<img width="1132" alt="Screen Shot 2019-11-16 at 6 48 21 PM" src="https://user-images.githubusercontent.com/57340720/69002337-0469fb00-08a2-11ea-9cb8-092c5aad9a7c.png">

**Comment by enoch85** [comment]
@giftedsheep Thanks for reporting.

It seems to be some PHP code error, I've transferred this issue to what I believe it might be. 

To answer your question, it's nothing serious.

**Comment by giftedsheep** [comment]
@enoch85 Thank you for your reply and thank you a lot for creating the VM! It was incredibly easy to set up for someone like me who does it for the first time. Another error that im getting is this one. Any need for panic?  
![Screen Shot 2019-11-17 at 1 07 46 PM](https://user-images.githubusercontent.com/57340720/69014117-b30e4a00-093b-11ea-9437-afcd7390860e.png)

**Comment by juliushaertl** [comment]
@enoch85 This is not related to the nextcloud-files repo (which is a js library)

Please open a new issue in the apps repo: https://github.com/icewind1991/files_snapshots
